"""strings - The STR table. Every UI label in the addon is looked up here.

Moved verbatim from the single-module addon; no body was edited during the move.
"""


# [ANCHOR: LOCALIZATION_STRINGS]
# ============================================================
STR = {
    # Operator Labels & Reports
    "op_copy_col_label": "Copy Col 1 to All",
    "op_copy_col_desc": "Copy Column 1 zone configuration to all other columns",
    "op_copy_col_done": "Column 1 replicated across all columns",
    "op_expand_secs_label": "Expand/Collapse Sections",
    "op_expand_secs_desc": "Open or close every section block in this list",
    "op_save_preset_label": "Save Preset",
    "op_save_preset_err_empty": "Preset name cannot be empty",
    "op_preset_err_bad_name": "Invalid preset name '{name}'",
    "op_save_preset_done": "Preset '{name}' saved successfully",
    "op_save_preset_err": "Failed to save preset: {err}",
    "op_load_preset_label": "Load Preset",
    "op_load_preset_warn_none": "No preset selected",
    "op_load_preset_err_not_found": "Preset file '{name}.json' not found",
    "op_load_preset_done": "Preset '{name}' loaded successfully",
    "op_load_preset_err": "Failed to load preset: {err}",
    "op_del_preset_label": "Delete Preset",
    "op_del_preset_warn_none": "No preset selected to delete",
    "op_del_preset_done": "Preset '{name}' deleted",
    "op_del_preset_err": "Failed to delete preset: {err}",
    "op_copy_lower_label": "Copy Lower to Upper",
    "op_copy_lower_done": "Lower sections copied to upper",
    "op_gen_label": "Generate Furniture",
    "op_gen_done": "Furniture '{id}' generated successfully",

    # Preset System
    "preset_none_title": "No presets found",
    "preset_none_desc": "Save a preset first",
    "preset_file_desc": "Preset file: {file}",

    # Enums: Shelf Bay Height Modes
    "enum_bay_mode_pct": "%",
    "enum_bay_mode_pct_desc": "Relative share in percentage",
    "enum_bay_mode_m": "m",
    "enum_bay_mode_m_desc": "Fixed height in meters",
    "enum_bay_mode_auto": "Auto",
    "enum_bay_mode_auto_desc": "Evenly fill remaining space",

    # Enums: Cabinet Zone Types
    "enum_zone_drawer": "Drawer",
    "enum_zone_drawer_desc": "Pull-out drawer box with facade",
    "enum_zone_door": "Door",
    "enum_zone_door_desc": "Hinged door compartment",
    "enum_zone_open": "Open Niche",
    "enum_zone_open_desc": "Open shelf compartment without doors",

    # Enums: Cabinet Zone Height Mode
    "enum_zone_h_meters": "Meters",
    "enum_zone_h_meters_desc": "Exact height in meters",
    "enum_zone_h_pct": "% Height",
    "enum_zone_h_pct_desc": "Percentage of available column space",
    "enum_zone_h_auto": "Auto",
    "enum_zone_h_auto_desc": "Automatically fill remaining space",

    # Enums: Door Swing
    "enum_swing_left": "Left Hinge",
    "enum_swing_left_desc": "Hinges on left side",
    "enum_swing_right": "Right Hinge",
    "enum_swing_right_desc": "Hinges on right side",
    "enum_swing_pair": "Double Door",
    "enum_swing_pair_desc": "Pair of doors meeting in center",

    # Enums: Handle Position
    "enum_hpos_top": "Top",
    "enum_hpos_top_desc": "Place handle near top edge",
    "enum_hpos_center": "Center",
    "enum_hpos_center_desc": "Place handle in vertical center",
    "enum_hpos_bottom": "Bottom",
    "enum_hpos_bottom_desc": "Place handle near bottom edge",

    # Enums: Handle Length Mode
    "enum_hlen_default": "Default",
    "enum_hlen_default_desc": "Use global handle length",
    "enum_hlen_pct": "% Height",
    "enum_hlen_pct_desc": "Scale handle length as percentage of door height",
    "enum_hlen_explicit": "Meters",
    "enum_hlen_explicit_desc": "Set explicit handle length in meters",

    # Enums: Interior Type
    "enum_interior_shelves": "Shelves",
    "enum_interior_shelves_desc": "Evenly distributed or custom shelf boards",
    "enum_interior_rod": "Clothes Rod",
    "enum_interior_rod_desc": "Hinged rail for clothes hangers",
    "enum_interior_empty": "Empty",
    "enum_interior_empty_desc": "Clear open volume",

    # Enums: Shelf Spacing
    "enum_shelf_even": "Evenly Spaced",
    "enum_shelf_even_desc": "Even step between shelves",
    "enum_shelf_custom": "Custom Bays",
    "enum_shelf_custom_desc": "Custom heights per compartment",

    # Enums: Section Types
    "enum_sec_normal": "Normal",
    "enum_sec_normal_desc": "Standard cabinet with doors/shelves",
    "enum_sec_wardrobe": "Wardrobe",
    "enum_sec_wardrobe_desc": "Wardrobe / Dresser with columns and vertical zones",
    "enum_sec_corner": "Corner",
    "enum_sec_corner_desc": "Corner cabinet module",
    "enum_sec_appliance": "Appliance",
    "enum_sec_appliance_desc": "Empty carcass / hood carcass",
    "enum_sec_hood_gap": "Hood Gap",
    "enum_sec_hood_gap_desc": "Skip space for external hood",
    "enum_sec_sink": "Sink",
    "enum_sec_sink_desc": "Doors, no shelves, countertop cutout",

    # Enums: Corner Style
    "enum_corn_diag": "Diagonal (45°)",
    "enum_corn_diag_desc": "Beveled face with single diagonal door",
    "enum_corn_doors": "L-Doors",
    "enum_corn_doors_desc": "Two doors meeting at inside corner",
    "enum_corn_blind": "Blind Panels",
    "enum_corn_blind_desc": "Closed dummy L-panels",
    "enum_corn_open": "Open Niche",
    "enum_corn_open_desc": "Open corner shelves without doors",

    # Enums: Handle Orientation
    "enum_horient_auto": "Default",
    "enum_horient_auto_desc": "Use global setting",
    "enum_horient_horiz": "Horizontal",
    "enum_horient_horiz_desc": "Force horizontal handle",
    "enum_horient_vert": "Vertical",
    "enum_horient_vert_desc": "Force vertical handle",

    # Properties: Names & Descriptions
    "prop_dividers": "Dividers",
    "prop_mode": "Mode",
    "prop_height": "Height",
    "prop_share_pct": "Share %",
    "prop_expanded": "Expanded",
    "prop_zone_type": "Zone Type",
    "prop_height_mode": "Height Mode",
    "prop_height_pct": "Height %",
    "prop_door_swing": "Door Swing",
    "prop_handle_pos": "Handle Pos",
    "prop_edge_dist": "Edge Dist",
    "prop_edge_dist_desc": "Exact distance from the chosen edge into the door",
    "prop_handle_len_mode": "Handle Length Mode",
    "prop_handle_pct": "Length %",
    "prop_handle_custom_len": "Length",
    "prop_interior": "Interior",
    "prop_shelf_spacing": "Shelf Spacing",
    "prop_shelves": "Shelves",
    "prop_bays": "Bays",
    "prop_rod_drop": "Rod Drop",
    "prop_zones": "Zones",
    "prop_width": "Width",
    "prop_sec_type": "Type",
    "prop_corner_style": "Corner Style",
    "prop_corner_sec": "Corner Section",
    "prop_custom_height": "Custom Height",
    "prop_custom_depth": "Custom Depth",
    "prop_depth": "Depth",
    "prop_columns": "Columns",
    "prop_bottom_panel": "Bottom Panel",
    "prop_top_panel": "Top Panel",
    "prop_has_back_panel": "Back Panel",
    "prop_use_legs": "Legs Instead of Plinth",
    "prop_leg_height": "Leg Height",
    "prop_horiz_shelves": "Horizontal Shelves",
    "prop_no_side_walls": "No Side Walls",
    "prop_no_side_walls_tip": "Drop both side walls: the section shares the walls of its neighbours. Ignored on the first and the last section of a row",
    "prop_shelves_span_walls": "Shelves to Walls",
    "prop_shelves_span_walls_tip": "Run the shelves into the neighbour sections up to the inner face of the nearest side wall on each side",
    "prop_z_anchor": "Anchor",
    "enum_z_anchor_auto": "Auto",
    "enum_z_anchor_auto_desc": "Upper row hangs from the row top, lower row stands on its plinth",
    "enum_z_anchor_bottom": "From Bottom",
    "enum_z_anchor_bottom_desc": "The section sits on the bottom line of the row; the offset is measured upward from it",
    "enum_z_anchor_top": "From Top",
    "enum_z_anchor_top_desc": "The section hangs from the top line of the row; the offset is measured downward from it",
    "prop_z_offset": "Offset",
    "prop_z_offset_tip": "Shift from the anchored edge. Positive is up with 'From Bottom', down with 'From Top'",
    "prop_doors": "Doors",
    "prop_handle_orient": "Handle Orientation",
    "prop_custom_handle_h": "Custom Handle Height",
    "prop_offset": "Offset",
    "prop_mid_divider": "Mid Divider",
    "prop_shelf_thickness": "Shelf Thickness",
    "prop_drawer_count": "Drawer Count",
    "prop_drawer_h": "Drawer Zone Height",
    "prop_sink_w": "Sink Width",
    "prop_sink_d": "Sink Depth",
    "prop_sink_margin_f": "Margin Front",
    "prop_sink_margin_b": "Margin Back",
    "prop_sink_margin_l": "Margin Left",
    "prop_sink_margin_r": "Margin Right",
    "prop_sink_recess_depth": "Recess Depth",
    "prop_sink_recess_margin_f": "Recess Margin Front",
    "prop_sink_recess_margin_b": "Recess Margin Back",
    "prop_sink_recess_margin_l": "Recess Margin Left",
    "prop_sink_recess_margin_r": "Recess Margin Right",
    "prop_sink_bevel_floor_w": "Floor Bevel Width",
    "prop_sink_bevel_vert_w": "Vertical Bevel Width",
    "prop_sink_bevel_top_w": "Top Bevel Width",
    "prop_sink_bevel_segments": "Bevel Segments",
    "prop_sink_bevel_miter": "Bevel Miter",
    "enum_bevel_miter_sharp": "Sharp",
    "enum_bevel_miter_arc": "Arc",
    "prop_sink_drain_on": "Drain",
    "prop_sink_drain_d1": "Drain Depth 1",
    "prop_sink_drain_d2": "Drain Depth 2",
    "prop_sink_drain_dia1": "Drain Diameter 1",
    "prop_sink_drain_dia2": "Drain Diameter 2",
    "prop_sink_drain_bevel_top": "Drain Bevel Top",
    "prop_sink_drain_bevel_mid": "Drain Bevel Middle",
    "prop_sink_drain_bevel_low": "Drain Bevel Bottom",
    "prop_sink_drain_bevel_segments": "Drain Bevel Segments",
    "prop_sink_strainer_on": "Strainer",
    "prop_sink_strainer_thickness": "Strainer Thickness",
    "prop_sink_strainer_gap": "Strainer Height",
    "prop_override_mat": "Override Materials",
    "prop_custom_facade": "Custom Facade",
    "prop_custom_carcass": "Custom Carcass",
    "prop_is_island": "Island Mode",
    "prop_has_upstand": "Wall Upstand",

    # Generator Global Properties
    "prop_preset_name": "Preset Name",
    "prop_preset_enum": "Presets",
    "prop_kitchen_id": "Furniture ID",
    "prop_wall_thickness": "Wall Thickness",
    "prop_gap": "Gap",
    "prop_enable_bevel": "Enable Bevel",
    "prop_bevel_width": "Width",
    "prop_bevel_segments": "Segments",
    "prop_gen_collisions": "Generate Collisions (UBX)",
    "prop_live_preview": "Live Preview",
    "prop_live_preview_desc": ("Rebuild automatically about a third of a second after a parameter stops changing. "
                               "Colliders are not built live - press Generate for them"),
    "ui_live_note": "Live preview skips colliders - Generate builds the full set",
    "ui_gen_collisions_note": ("Extra boxes, slow the build. Turn on after the last rebuild, right before Bake"),
    "prop_sections": "Sections",
    "prop_carcass_height": "Carcass Height",
    "prop_plinth_height": "Plinth Height",
    "prop_plinth_recess": "Plinth Recess",
    "prop_countertop_thickness": "Thickness",
    "prop_countertop_over_front": "Front Overhang",
    "prop_countertop_over_back": "Back Overhang (Island)",
    "prop_countertop_over_side": "Side Overhang",
    "prop_island_corner_radius": "Island Corner Radius",
    "prop_upstand_height": "Upstand Height",
    "prop_upstand_thickness": "Upstand Thickness",
    "prop_gen_upper": "Generate Wall Cabinets",
    "prop_sync_upper": "Sync with Lower",
    "prop_upper_sections": "Upper Sections",
    "prop_backsplash_gap": "Backsplash Gap",
    "prop_upper_handle_z": "Upper Handle Z Offset",
    "prop_vert_handles": "Vertical Handles",
    "prop_handle_length": "Length",
    "prop_handle_bar_overhang": "Bar Overhang",
    "prop_handle_bar_radius": "Bar Radius",
    "prop_handle_mount_len": "Mount Length",
    "prop_handle_side_margin": "Side Margin",
    "prop_lower_handle_top_margin": "Lower Top Margin",
    "prop_upper_handle_bottom_margin": "Upper Bottom Margin",
    "prop_handle_z_fine": "Z Fine-tune Offset",
    "prop_drawer_handle_scale": "Drawer Handle Scale",
    "prop_mat_facade_lower": "Lower Facade",
    "prop_mat_facade_upper": "Upper Facade",
    "prop_mat_carcass": "Carcass & Shelves",
    "prop_mat_countertop": "Countertop",
    "prop_mat_plinth": "Plinth",
    "prop_mat_handle": "Handle",
    "prop_tile_u": "Tile U",
    "prop_tile_v": "Tile V",
    "prop_rotate_90": "Rotate 90°",

    # UI Panel Titles & Categories
    "panel_category": "Furniture",
    "panel_main_title": "Furniture Generator",
    "panel_bevel_title": "Bevel & Chamfer (UE Normals)",
    "panel_general_title": "General & Export (UE)",
    "panel_carcass_title": "Carcass & Global Dimensions",
    "panel_sections_title": "Sections & Wardrobe Grid",
    "panel_upper_global_title": "Upper Cabinets (Wall)",
    "panel_upper_sections_title": "Upper Sections List",
    "panel_countertop_title": "Countertop & Wall Upstand",
    "panel_handles_title": "Handles",
    "panel_materials_title": "Materials & UV Tiling",
    "panel_debug_title": "Debug Scenes (One-Click Build)",
    "panel_bake_title": "Bake for Export (UE)",

    # UI Controls & Elements
    "ui_presets_manager": "Presets Manager",
    "ui_load": "Load",
    "ui_save": "Save",
    "ui_generate_btn": "Generate All Modules",
    "ui_bake_btn": "Bake for Export",
    "ui_export_fbx_btn": "Export FBX & Tables",
    "ui_version": "Addon v{v}",
    "ui_section_prefix": "Section {num}",
    "ui_upper_section_prefix": "Upper Section {num}",
    "ui_col_vertical_zones": "Columns & Vertical Zones",
    "ui_expand_all": "Expand All",
    "ui_collapse_all": "Collapse All",
    "ui_show_uv_details": "UV Tiling & Rotation",
    "ui_show_uv_details_desc": "Show U/V tiling and rotation for every material slot",
    "ui_copy_col1_all": "Copy Col 1 -> All",
    "ui_column_prefix": "Column {num}",
    "ui_hinge": "Hinge",
    "ui_inside": "Inside",
    "ui_handle": "Handle",
    "ui_shift": "Shift",
    "ui_edge_dist": "Edge Dist",
    "ui_length": "Length",
    "ui_size": "Size",
    "ui_step": "Step",
    "ui_compartment_heights": "Compartment Heights (Top to Bottom)",
    "ui_bay_prefix": "Bay {num}",
    "ui_tier_dividers": "Tier {num} Dividers",
    "ui_facade_mat": "Facade Mat",
    "ui_carcass_mat": "Carcass Mat",
    "ui_hood_gap_label": "Hood Gap (Empty space)",
    "ui_mat_lower_facades": "Lower Facades (Doors/Drawers)",
    "ui_mat_upper_facades": "Upper Facades (Wall Doors)",
    "ui_mat_carcass_shelves": "Carcass & Shelves",
    "ui_mat_countertop": "Countertop",
    "ui_mat_plinth": "Plinth",
    "ui_mat_handles": "Handles",

    # Debug scene panel
    "op_debug_scene_label": "Build Debug Scene",
    "op_bake_label": "Bake for Export",
    "op_bake_done": "Bake complete: see the BAKE collection and the report file",
    "op_bake_no_source": "Nothing to bake: generate the kitchen first",
    "op_bake_name_bad": "Bake name must differ from the kitchen id",
    "op_export_fbx_label": "Export FBX & Tables",
    "op_export_fbx_desc": ("Bake, export the BAKE collection to FBX with its "
                           "SOCKET_ empties, and write the CSV/TXT tables "
                           "next to the file"),
    "op_export_fbx_no_path": "Pick a file path for the FBX first",
    "op_export_fbx_no_source": "Nothing to export: generate the kitchen first",
    "op_export_fbx_no_collection": "Bake produced no BAKE collection to export",
    "op_export_fbx_failed": "FBX export failed, see the terminal for the reason",
    "op_export_fbx_tables_missing": "FBX written, but not every table could be saved",
    "op_export_fbx_done": "FBX and tables written",
    "prop_bake_name": "Bake Name (SM_ Prefix)",
    "prop_bake_split_upper": "Split Upper Body",
    "op_debug_scene_desc": "Apply a fixed set of parameters and rebuild, to inspect one scenario visually",
    "op_debug_scene_err_unknown": "Unknown debug scene '{key}'",
    "op_debug_scene_err_apply": "Scene '{name}' rejected: {err}",
    "op_debug_scene_params_only": "'{name}': parameters applied, generation skipped",
    "op_debug_scene_done": "'{name}' built",
    "ui_debug_auto": "Generate After Applying",
    "ui_debug_auto_desc": "Off: the button only sets the parameters, so they can be checked or tweaked first",
    "ui_debug_last": "Built from: {name}",
    "ui_debug_never": "Nothing built yet this session",
    "ui_debug_note": "Each button resets the sections it touches, so scenarios never inherit state from each other",
    "ui_debug_group_rows": "Rows",
    "ui_debug_group_corners": "Corner Styles",
    "ui_debug_group_specials": "Special Cases",
}

# ============================================================
